export const STORE_CONFIG = {
  currency: "USD",
  reservationMinutes: 30,
  staffPin: import.meta.env.VITE_STORE_STAFF_PIN || "2468",
  demoVisitor: {
    name: "Carlos Rivera",
    phone: "+1 555 0148",
    segment: "Cisco Live attendee",
    source: "Cisco Spaces captive portal",
  },
};

export const products = [
  {
    id: "cisco02611",
    sku: "CISCO02611",
    name: "Hybrid Work Gears T-Shirt Black (Unisex)",
    collection: "Hatch Design",
    category: "Apparel",
    price: 26.99,
    visualType: "tee",
    accent: "#1f2937",
    image:
      "https://merchandise-cisco.b-cdn.net/media/catalog/product/cache/3788aaff41c1891c82645e877f66aa7d/h/y/hybrid_work_gears_t-shirt_1.jpg",
    productUrl: "https://merchandise.cisco.com/cisco02611.html",
    description: "Unisex pocket crew tee with Hybrid Work graphics.",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
  },
  {
    id: "cisco02403",
    sku: "CISCO02403",
    name: "Dunes T-Shirt Coal (Unisex)",
    collection: "Hatch Design",
    category: "Apparel",
    price: 26.99,
    visualType: "tee",
    accent: "#30323d",
    image:
      "https://merchandise-cisco.b-cdn.net/media/catalog/product/cache/3788aaff41c1891c82645e877f66aa7d/d/u/dunes_coal_t-shirt.jpg",
    productUrl: "https://merchandise.cisco.com/cisco02403.html",
    description: "Relaxed-fit Cisco graphic t-shirt in coal.",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
  },
  {
    id: "cisco02330",
    sku: "CISCO02330",
    name: "Harbor Shirt Light Blue (Men's)",
    collection: "Cisco Store",
    category: "Apparel",
    price: 62.99,
    visualType: "shirt",
    accent: "#76bde8",
    image:
      "https://merchandise-cisco.b-cdn.net/media/catalog/product/cache/3788aaff41c1891c82645e877f66aa7d/c/i/cisco02330.png",
    productUrl: "https://merchandise.cisco.com/cisco02330.html",
    description: "Short-sleeve button down made with recycled polyester.",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
  },
  {
    id: "cisco02777",
    sku: "CISCO02777",
    name: "Riviera Shirt Multi Color Tines (Men's)",
    collection: "Cisco Store",
    category: "Apparel",
    price: 62.99,
    visualType: "shirt",
    accent: "#f28d35",
    image:
      "https://merchandise-cisco.b-cdn.net/media/catalog/product/cache/2ab59e795355d47654a6e98d116935c7/c/i/cisco02779-1_1_.jpg",
    productUrl: "https://merchandise.cisco.com/cisco02777.html",
    description: "Statement button-down shirt for the event floor.",
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
  },
  {
    id: "cisco04041",
    sku: "CISCO04041",
    name: "Gradient Bridge Water Bottle - Black",
    collection: "Crafted by Creative Studio",
    category: "Drinkware",
    price: 21.99,
    visualType: "bottle",
    accent: "#0f172a",
    image:
      "https://merchandise-cisco.b-cdn.net/media/catalog/product/cache/2ab59e795355d47654a6e98d116935c7/c/i/cisco04041.png",
    productUrl: "https://merchandise.cisco.com/cisco04041.html",
    description: "30 oz insulated stainless steel bottle with gradient bridge art.",
    sizes: ["OS"],
  },
  {
    id: "cisco03764",
    sku: "CISCO03764",
    name: "Core Slique Tumbler - Black",
    collection: "Core",
    category: "Drinkware",
    price: 14.99,
    visualType: "bottle",
    accent: "#111827",
    image:
      "https://merchandise-cisco.b-cdn.net/media/catalog/product/cache/2ab59e795355d47654a6e98d116935c7/c/i/cisco03764.png",
    productUrl: "https://merchandise.cisco.com/cisco03764.html",
    description: "18 oz matte tumbler with straw, lid, and Cisco logo.",
    sizes: ["OS"],
  },
  {
    id: "cisco0007",
    sku: "CISCO0007",
    name: "Classic Lapel Pin",
    collection: "Cisco",
    category: "Collectibles",
    price: 7.99,
    visualType: "pin",
    accent: "#0d6efd",
    image:
      "https://merchandise-cisco.b-cdn.net/media/catalog/product/cache/2ab59e795355d47654a6e98d116935c7/p/i/pin_badge_cisco.jpg",
    productUrl: "https://merchandise.cisco.com/cisco0007.html",
    description: "Small lapel pin for badges, lanyards, and gifts.",
    sizes: ["OS"],
  },
];

export const bundles = [
  {
    id: "first-timer-kit",
    name: "First Timer Kit",
    description: "Hybrid Work tee, Classic Lapel Pin, and Gradient Bridge bottle.",
    items: [
      { productId: "cisco02611", size: "M", quantity: 1 },
      { productId: "cisco0007", size: "OS", quantity: 1 },
      { productId: "cisco04041", size: "OS", quantity: 1 },
    ],
  },
  {
    id: "event-floor-fit",
    name: "Event Floor Fit",
    description: "Harbor shirt, Slique tumbler, and Classic Lapel Pin.",
    items: [
      { productId: "cisco02330", size: "L", quantity: 1 },
      { productId: "cisco03764", size: "OS", quantity: 1 },
      { productId: "cisco0007", size: "OS", quantity: 1 },
    ],
  },
  {
    id: "team-gift-pack",
    name: "Team Gift Pack",
    description: "Four pins and two drinkware pieces for a small team.",
    items: [
      { productId: "cisco0007", size: "OS", quantity: 4 },
      { productId: "cisco04041", size: "OS", quantity: 1 },
      { productId: "cisco03764", size: "OS", quantity: 1 },
    ],
  },
];

export const inventorySeed = [
  { productId: "cisco02611", size: "S", onHand: 10 },
  { productId: "cisco02611", size: "M", onHand: 16 },
  { productId: "cisco02611", size: "L", onHand: 14 },
  { productId: "cisco02611", size: "XL", onHand: 8 },
  { productId: "cisco02611", size: "XXL", onHand: 5 },
  { productId: "cisco02611", size: "XXXL", onHand: 3 },
  { productId: "cisco02403", size: "S", onHand: 7 },
  { productId: "cisco02403", size: "M", onHand: 13 },
  { productId: "cisco02403", size: "L", onHand: 11 },
  { productId: "cisco02403", size: "XL", onHand: 6 },
  { productId: "cisco02403", size: "XXL", onHand: 4 },
  { productId: "cisco02403", size: "XXXL", onHand: 2 },
  { productId: "cisco02330", size: "S", onHand: 4 },
  { productId: "cisco02330", size: "M", onHand: 7 },
  { productId: "cisco02330", size: "L", onHand: 6 },
  { productId: "cisco02330", size: "XL", onHand: 5 },
  { productId: "cisco02330", size: "XXL", onHand: 2 },
  { productId: "cisco02330", size: "XXXL", onHand: 1 },
  { productId: "cisco02777", size: "S", onHand: 3 },
  { productId: "cisco02777", size: "M", onHand: 5 },
  { productId: "cisco02777", size: "L", onHand: 6 },
  { productId: "cisco02777", size: "XL", onHand: 4 },
  { productId: "cisco02777", size: "XXL", onHand: 2 },
  { productId: "cisco02777", size: "XXXL", onHand: 1 },
  { productId: "cisco04041", size: "OS", onHand: 18 },
  { productId: "cisco03764", size: "OS", onHand: 14 },
  { productId: "cisco0007", size: "OS", onHand: 42 },
];
